export const COUNTRY_PHONE_CODES: Record<string, { code: string; digits: number }> = {
    "Afghanistan": { code: "+93", digits: 9 },
    "Albania": { code: "+355", digits: 9 },
    "Algeria": { code: "+213", digits: 9 },
    "Andorra": { code: "+376", digits: 6 },
    "Angola": { code: "+244", digits: 9 },
    "Antigua and Barbuda": { code: "+1", digits: 10 },
    "Argentina": { code: "+54", digits: 10 },
    "Armenia": { code: "+374", digits: 8 },
    "Australia": { code: "+61", digits: 9 },
    "Austria": { code: "+43", digits: 10 },
    "Azerbaijan": { code: "+994", digits: 9 },
    "Bahamas": { code: "+1", digits: 10 },
    "Bahrain": { code: "+973", digits: 8 },
    "Bangladesh": { code: "+880", digits: 10 },
    "Barbados": { code: "+1", digits: 10 },
    "Belarus": { code: "+375", digits: 9 },
    "Belgium": { code: "+32", digits: 9 },
    "Belize": { code: "+501", digits: 7 },
    "Benin": { code: "+229", digits: 8 },
    "Bhutan": { code: "+975", digits: 8 },
    "Bolivia": { code: "+591", digits: 8 },
    "Bosnia and Herzegovina": { code: "+387", digits: 8 },
    "Botswana": { code: "+267", digits: 8 },
    "Brazil": { code: "+55", digits: 11 },
    "Brunei": { code: "+673", digits: 7 },
    "Bulgaria": { code: "+359", digits: 9 },
    "Burkina Faso": { code: "+226", digits: 8 },
    "Burundi": { code: "+257", digits: 8 },
    "Cabo Verde": { code: "+238", digits: 7 },
    "Cambodia": { code: "+855", digits: 8 },
    "Cameroon": { code: "+237", digits: 9 },
    "Canada": { code: "+1", digits: 10 },
    "Central African Republic": { code: "+236", digits: 8 },
    "Chad": { code: "+235", digits: 8 },
    "Chile": { code: "+56", digits: 9 },
    "China": { code: "+86", digits: 11 },
    "Colombia": { code: "+57", digits: 10 },
    "Comoros": { code: "+269", digits: 7 },
    "Congo (Congo-Brazzaville)": { code: "+242", digits: 9 },
    "Costa Rica": { code: "+506", digits: 8 },
    "Croatia": { code: "+385", digits: 9 },
    "Cuba": { code: "+53", digits: 8 },
    "Cyprus": { code: "+357", digits: 8 },
    "Czech Republic": { code: "+420", digits: 9 },
    "Democratic Republic of the Congo": { code: "+243", digits: 9 },
    "Denmark": { code: "+45", digits: 8 },
    "Djibouti": { code: "+253", digits: 8 },
    "Dominica": { code: "+1", digits: 10 },
    "Dominican Republic": { code: "+1", digits: 10 },
    "Ecuador": { code: "+593", digits: 9 },
    "Egypt": { code: "+20", digits: 10 },
    "El Salvador": { code: "+503", digits: 8 },
    "Equatorial Guinea": { code: "+240", digits: 9 },
    "Eritrea": { code: "+291", digits: 7 },
    "Estonia": { code: "+372", digits: 7 },
    "Eswatini": { code: "+268", digits: 8 },
    "Ethiopia": { code: "+251", digits: 9 },
    "Fiji": { code: "+679", digits: 7 },
    "Finland": { code: "+358", digits: 9 },
    "France": { code: "+33", digits: 9 },
    "Gabon": { code: "+241", digits: 7 },
    "Gambia": { code: "+220", digits: 7 },
    "Georgia": { code: "+995", digits: 9 },
    "Germany": { code: "+49", digits: 10 },
    "Ghana": { code: "+233", digits: 9 },
    "Greece": { code: "+30", digits: 10 },
    "Grenada": { code: "+1", digits: 10 },
    "Guatemala": { code: "+502", digits: 8 },
    "Guinea": { code: "+224", digits: 9 },
    "Guinea-Bissau": { code: "+245", digits: 9 },
    "Guyana": { code: "+592", digits: 7 },
    "Haiti": { code: "+509", digits: 8 },
    "Honduras": { code: "+504", digits: 8 },
    "Hungary": { code: "+36", digits: 9 },
    "Iceland": { code: "+354", digits: 7 },
    "India": { code: "+91", digits: 10 },
    "Indonesia": { code: "+62", digits: 10 },
    "Iran": { code: "+98", digits: 10 },
    "Iraq": { code: "+964", digits: 10 },
    "Ireland": { code: "+353", digits: 9 },
    "Israel": { code: "+972", digits: 9 },
    "Italy": { code: "+39", digits: 10 },
    "Ivory Coast": { code: "+225", digits: 10 },
    "Jamaica": { code: "+1", digits: 10 },
    "Japan": { code: "+81", digits: 10 },
    "Jordan": { code: "+962", digits: 9 },
    "Kazakhstan": { code: "+7", digits: 10 },
    "Kenya": { code: "+254", digits: 9 },
    "Kiribati": { code: "+686", digits: 5 },
    "Kuwait": { code: "+965", digits: 8 },
    "Kyrgyzstan": { code: "+996", digits: 9 },
    "Laos": { code: "+856", digits: 10 },
    "Latvia": { code: "+371", digits: 8 },
    "Lebanon": { code: "+961", digits: 8 },
    "Lesotho": { code: "+266", digits: 8 },
    "Liberia": { code: "+231", digits: 7 },
    "Libya": { code: "+218", digits: 9 },
    "Liechtenstein": { code: "+423", digits: 7 },
    "Lithuania": { code: "+370", digits: 8 },
    "Luxembourg": { code: "+352", digits: 9 },
    "Madagascar": { code: "+261", digits: 9 },
    "Malawi": { code: "+265", digits: 9 },
    "Malaysia": { code: "+60", digits: 9 },
    "Maldives": { code: "+960", digits: 7 },
    "Mali": { code: "+223", digits: 8 },
    "Malta": { code: "+356", digits: 8 },
    "Marshall Islands": { code: "+692", digits: 7 },
    "Mauritania": { code: "+222", digits: 8 },
    "Mauritius": { code: "+230", digits: 8 },
    "Mexico": { code: "+52", digits: 10 },
    "Micronesia": { code: "+691", digits: 7 },
    "Moldova": { code: "+373", digits: 8 },
    "Monaco": { code: "+377", digits: 8 },
    "Mongolia": { code: "+976", digits: 8 },
    "Montenegro": { code: "+382", digits: 8 },
    "Morocco": { code: "+212", digits: 9 },
    "Mozambique": { code: "+258", digits: 9 },
    "Myanmar": { code: "+95", digits: 9 },
    "Namibia": { code: "+264", digits: 9 },
    "Nauru": { code: "+674", digits: 7 },
    "Nepal": { code: "+977", digits: 10 },
    "Netherlands": { code: "+31", digits: 9 },
    "New Zealand": { code: "+64", digits: 9 },
    "Nicaragua": { code: "+505", digits: 8 },
    "Niger": { code: "+227", digits: 8 },
    "Nigeria": { code: "+234", digits: 10 },
    "North Korea": { code: "+850", digits: 10 },
    "North Macedonia": { code: "+389", digits: 8 },
    "Norway": { code: "+47", digits: 8 },
    "Oman": { code: "+968", digits: 8 },
    "Pakistan": { code: "+92", digits: 10 },
    "Palau": { code: "+680", digits: 7 },
    "Palestine": { code: "+970", digits: 9 },
    "Panama": { code: "+507", digits: 8 },
    "Papua New Guinea": { code: "+675", digits: 8 },
    "Paraguay": { code: "+595", digits: 9 },
    "Peru": { code: "+51", digits: 9 },
    "Philippines": { code: "+63", digits: 10 },
    "Poland": { code: "+48", digits: 9 },
    "Portugal": { code: "+351", digits: 9 },
    "Qatar": { code: "+974", digits: 8 },
    "Romania": { code: "+40", digits: 9 },
    "Russia": { code: "+7", digits: 10 },
    "Rwanda": { code: "+250", digits: 9 },
    "Saint Kitts and Nevis": { code: "+1", digits: 10 },
    "Saint Lucia": { code: "+1", digits: 10 },
    "Saint Vincent and the Grenadines": { code: "+1", digits: 10 },
    "Samoa": { code: "+685", digits: 5 },
    "San Marino": { code: "+378", digits: 10 },
    "Sao Tome and Principe": { code: "+239", digits: 7 },
    "Saudi Arabia": { code: "+966", digits: 9 },
    "Senegal": { code: "+221", digits: 9 },
    "Serbia": { code: "+381", digits: 8 },
    "Seychelles": { code: "+248", digits: 7 },
    "Sierra Leone": { code: "+232", digits: 8 },
    "Singapore": { code: "+65", digits: 8 },
    "Slovakia": { code: "+421", digits: 9 },
    "Slovenia": { code: "+386", digits: 8 },
    "Solomon Islands": { code: "+677", digits: 7 },
    "Somalia": { code: "+252", digits: 8 },
    "South Africa": { code: "+27", digits: 9 },
    "South Korea": { code: "+82", digits: 10 },
    "South Sudan": { code: "+211", digits: 9 },
    "Spain": { code: "+34", digits: 9 },
    "Sri Lanka": { code: "+94", digits: 9 },
    "Sudan": { code: "+249", digits: 9 },
    "Suriname": { code: "+597", digits: 7 },
    "Sweden": { code: "+46", digits: 9 },
    "Switzerland": { code: "+41", digits: 9 },
    "Syria": { code: "+963", digits: 9 },
    "Taiwan": { code: "+886", digits: 9 },
    "Tajikistan": { code: "+992", digits: 9 },
    "Tanzania": { code: "+255", digits: 9 },
    "Thailand": { code: "+66", digits: 9 },
    "Timor-Leste": { code: "+670", digits: 8 },
    "Togo": { code: "+228", digits: 8 },
    "Tonga": { code: "+676", digits: 5 },
    "Trinidad and Tobago": { code: "+1", digits: 10 },
    "Tunisia": { code: "+216", digits: 8 },
    "Turkey": { code: "+90", digits: 10 },
    "Turkmenistan": { code: "+993", digits: 8 },
    "Tuvalu": { code: "+688", digits: 5 },
    "Uganda": { code: "+256", digits: 9 },
    "Ukraine": { code: "+380", digits: 9 },
    "United Arab Emirates": { code: "+971", digits: 9 },
    "United Kingdom": { code: "+44", digits: 10 },
    "United States": { code: "+1", digits: 10 },
    "Uruguay": { code: "+598", digits: 8 },
    "Uzbekistan": { code: "+998", digits: 9 },
    "Vanuatu": { code: "+678", digits: 7 },
    "Vatican City": { code: "+39", digits: 10 },
    "Venezuela": { code: "+58", digits: 10 },
    "Vietnam": { code: "+84", digits: 9 },
    "Yemen": { code: "+967", digits: 9 },
    "Zambia": { code: "+260", digits: 9 },
    "Zimbabwe": { code: "+263", digits: 9 }
}

export const COUNTRIES = Object.keys(COUNTRY_PHONE_CODES).sort()
